# Generated by Django 5.0.1 on 2024-01-27 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("boja", models.CharField(max_length=255)),
                ("novo", models.BooleanField(default=True)),
                ("cena", models.IntegerField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Dizajner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("prez", models.CharField(max_length=255)),
                ("zemja", models.CharField(max_length=255)),
                (
                    "parce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.parce"
                    ),
                ),
            ],
        ),
    ]
